### ISSUE TITLE
Getting TypeError: results.forEach is not a function

### ISSUE THREAD

**Issue by Nileshbirari** [coryhouse/javascript-development-environment#1]
Hi Cory,
I was following your course on pluralsight but facing an issue using Fetch
My repo
https://github.com/Nileshbirari/pluralsight-js-dev-env

TypeError: results.forEach is not a function when I am trying to load localhost:3000
When I run localhost:3000/users I get to see the list of users correctly

**Comment by coryhouse** [comment]
The variable results is undefined at line 5 in index.js. You need to set it to something.

**Comment by Nileshbirari** [comment]
My index.js look like this, results should contain value from getUsers() isn't it ? How to define it if at all ?
Am I missing something ?

1: import './index.css';
2. import {getUsers} from './api/userApi.js';
3. **getUsers().then(results => {**
4.let usersBody = "";
5. results.forEach(user => {
usersBody == `<tr>
<td><a href="#" data-id="${user.id} class="deleteUser">Delete</a></td>
<td>$(user.id)</td>
<td>$(user.fname)</td>
</td>$(user.lname)</td>
</tr>`
});
global.document.getElementById('users').innerHTML = usersBody;
});

**Comment by coryhouse** [comment]
Hi Nuri,

I'm sorry, I just realized I have a session I need to attend at 1 today so
I can't make the open space.

Please accept my apologies!
Cory

**Comment by YigalNissan** [comment]
Hi Cory,
First of all I would like to thank you very much for your wonderful course.
Although it's not suite for my developing level, it is very fruitful and it push me up the developing scale, hopefully one day to become an expert like you.  

Now I am having the same issue of "TypeError: result.forEach is not a function..",
and I do not understand what should I set result to ? and how to solve this issue.
Very appreciate your assistant.
Thanks
Yigal

**Comment by coryhouse** [comment]
Hi Yigal - Great to hear. Can you please post this question on the course discussion so others can benefit from my answer?

**Comment by YigalNissan** [comment]
Thanks Cory for your quick response.
I solved it using regular for loop, but i would like to understand why it's not working as it should.
I will follow your answer through the course threads.
