### ISSUE TITLE
npm start doesn't work 

### ISSUE THREAD

**Issue by sugandhgoyal** [coryhouse/javascript-development-environment#12]
`> javascript-development-environment@1.0.0 start G:\Pluralsight-JsDevEnv
> node buildScripts/srcServer.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1259:14)
    at listen (net.js:1295:10)
    at Server.listen (net.js:1391:5)
    at EventEmitter.listen (G:\Pluralsight-JsDevEnv\node_modules\express\lib\application.js:617:24)
    at Object.<anonymous> (G:\Pluralsight-JsDevEnv\buildScripts\srcServer.js:11:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! javascript-development-environment@1.0.0 start: `node buildScripts/srcServer.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the javascript-development-environment@1.0.0 start script 'node buildScripts/srcServer.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the javascript-development-environment package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node buildScripts/srcServer.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs javascript-development-environment
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls javascript-development-environment
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     G:\Pluralsight-JsDevEnv\npm-debug.log`

When I do npm start, it creates a debug.log fie with the same errors.

**Comment by coryhouse** [comment]
That error just means you already have something running on port 3000, likely another instance of this project in a different window. :)
