### ISSUE TITLE
npm test error

### ISSUE THREAD

**Issue by sugandhgoyal** [coryhouse/javascript-development-environment#13]
> javascript-development-environment@1.0.0 test G:\Pluralsight-JsDevEnv
> mocha --reporter progress buildScripts/testSetup.js "src/**/*.test.js"

Warning: Could not find any test files matching pattern: src/**/*.test.js
  0 passing (2ms)

Why does this give 0 passing?

**Comment by coryhouse** [comment]
This is just saying it can't find any test files. Create at least one test and this will go away.
