### ISSUE TITLE
Module 4:  nsp - but Node Security Platform service is shutting down 9/30 2018

### ISSUE THREAD

**Issue by knbknb** [coryhouse/javascript-development-environment#21]
After cloning this repo and doing `npm install` I just got this output on the command line:

` npm WARN deprecated nsp@2.6.2: The Node Security Platform service is shutting down 9/30 
`
See official announcement on [npm blog](https://blog.npmjs.org/post/175511531085/the-node-security-platform-service-is-shutting)

> npm now automatically reviews every install request against the NSP vulnerability database and warns you if you try to use unsafe code. Additionally, beginning with npm@6, a new command, `npm audit`, recursively analyzes your dependency trees to identify specifically what’s insecure, recommend a replacement, or fix it automatically with npm audit fix.

Can you update the README of the repo, or maybe even the pluralsight course video. Perhaps create a fly-in banner that tells users what to do instead of ? (I know that maybe that's not possible)

**Comment by coryhouse** [comment]
Thanks for the suggestion. Yes, I'll update the video accordingly. Thanks!

**Comment by coryhouse** [comment]
Hi Knut - I don't reference babel-node in the final course demo. Are you saying I suggested installing it at some point in the course? If so, can you point me to the clip?

**Comment by knbknb** [comment]
Take a look at Module 7 "Transpiling", video 7 "Demo: Set Up Babel" at 2min 10secs . It's a very brief section, editing a config file.

**Comment by coryhouse** [comment]
Ah, I see the confusion. Note that we never installed babel-node, because the `babel-node` command actually calls the babel-cli package, which we did install.

**Comment by coryhouse** [comment]
And regarding Yarn, I expect its popularity to continue to decrease. npm has added features to address most performance and feature differences, so there's little reason to choose Yarn anymore.

**Comment by knbknb** [comment]
Okay, so from my side there is not much to say anymore, and I don't mind if this issue is closed. That's up to you.

In the next days I'll continue with the course; I'm 25% through. When I find something else can reopen this issue. Or do you rather prefer that I use the course discussion page for comments like this?

**Comment by coryhouse** [comment]
I'll leave this issue open since I haven't patched the video regarding nsp yet. Feel free to post here. :) Thanks again for your candor!

**Comment by coryhouse** [comment]
I've patched the video to add a notification about this, so closing. Thanks @knbknb !
