### ISSUE TITLE
update devDependencies List/Table in README

### ISSUE THREAD

**Issue by knbknb** [coryhouse/javascript-development-environment#23]
In  the `README, md` file, the  devDependencies Table seems to be slightly out of sync with the `devDependencies` associative array  in `package.json`

I found explanations for these to be missing in the table  in `README.md`

-   chai
-   chalk
-   compression
-   html-webpack-plugin
-   json-schema-faker
-   json-server
-   localtunnel
-   nock
-   numeral
-  webpack-md5-hash

After running `npm install`, 've found these module directories to be missing in node_modules/ dir,
but they are mentioned in the README. 

- eventsource-polyfill        
- expect    
- file-loader 
- url-loader 

Maybe they are hidden inside different directory names. (I am not too familiar with the node ecosystem, and I didn't look to closely.  )

**Comment by coryhouse** [comment]
Wow, good eyes!  Changes up. Thanks for the detailed list!
