### ISSUE TITLE
security-check fails

### ISSUE THREAD

**Issue by gbm** [coryhouse/javascript-development-environment#24]
nsp check
(+) Client request error: getaddrinfo ENOTFOUND api.nodesecurity.io api.nodesecurity.io:443

(running nsp check here on it's own just to show the error)

**Comment by coryhouse** [comment]
nsp was acquired by npm, so it's now built into npm. You no longer need to manually run nsp. [Check out this PR](https://github.com/coryhouse/javascript-development-environment/pull/7/files) for updates on how to run the latest versions.

**Comment by gbm** [comment]
thx :) i would suggest either editing the course (which is great) or sticking up one of those blue post it notes

**Comment by Chris-43** [comment]
What in the hell is going on?

What part of my background is off?

I worked at the Jet Propulsion Laboratory for 25 years. I have held a
military security clearance for most of my life. I WAS happily subscribed
for months.

I will forward this mess to Cory.

**Comment by coryhouse** [comment]
I've already added a blue note to the relevant clips in the course. That note was added months ago. Did you guys just overlook it?

@Chris-43 - What is your issue?

**Comment by gbm** [comment]
I see what happened - yes you are right there is a blue note in the package management section but one is missing in the Automation - Demo: Create Security Check and Share Scripts. [only checking cos I love you ;) ]

**Comment by coryhouse** [comment]
@gbm - Ah! Great catch! I just submitted a patch to add a callout on that clip, and the following clip as well since it shows calling the security-check clip. Thanks! 💯
