### ISSUE TITLE
branch update-2019 README: add description how to merge with master. dotfiles gone

### ISSUE THREAD

**Issue by knbknb** [coryhouse/javascript-development-environment#34]
Thanks for creating the branch `update-2019`. I have and enhancement and a bug (missing dotfiles)
 
I have cloned the master branch of the repo https://github.com/coryhouse/javascript-development-environment like this:

```sh
git clone https://github.com/coryhouse/javascript-development-environment
git pull origin update-2019
```

Is this the correct sequence of git commands? 

- If so, it is not obvious from the README. (please add such a paragraph)
- If this is indeed correct (`npm run build -s` succeeds, tests are fine, the app runs with node 10, on localhost:3000 and localhost 3001), then this paragraph from the README is misleading:

> Make sure files with names that begin with a dot (.babelrc, .editorconfig, .eslintrc) are copied to the project directory root. This is easy to overlook if you copy this repository manually.

...because these dot-files are gone after the merge:

-  .babelrc  no longer exists, has been moved into into package.json (I'm fine with that)
- but `.editorconfig, .eslintrc` are gone (because they are not included in this branch)

I think `.editorconfig, .eslintrc` should be re-added to this branch. But maybe you have a better idea?

**Comment by coryhouse** [comment]
Thanks for the feedback! I deliberately removed the dotfiles because the config is now in package.json. And after you've cloned, the command to switch to this branch is:

`git checkout update-2019`

I added a note to the PR.

**Comment by knbknb** [comment]
thanks, but .... well .... Your explanation in paragraph "Having issues?.. Try these things first:" *still* mentions the dotfiles (in topic 3), and encourages your users to look for them to fix problems on their side. But the dotfiles are now gone on purpose. That is confusing, in my opinion.  Hence I thought It is better to remove topic 3 entirely. 

The README.md files should be updated in both branches, master and update-2019.  And `git checkout` just  switches the branch but does not merge them. I was more interested in the recommended merge commands (now I already know one way to to this). Perhaps you prefer users to checkout, but not merge, for some reason.

You can keep this closed, I couldn't be happier. For now, I don't have any problems with the update-2019 branch, dotfiles, the merge. I just thought mentioning this would make it a bit easier for other users (most of them  will still have issues)
